### ISSUE TITLE
Try to solve its error and turn it to https 

### ISSUE THREAD

**Issue by hamza94max** [hassaanjamil/hj-qibla-compass#6]
**maven { url "http://api.tplmaps.com:8081/artifactory/example-repo-local/" }**

makes an error

**Comment by moemura** [comment]
in settings.gradle add allowInsecureProtocol = true 


        maven {
            url "http://api.tplmaps.com:8081/artifactory/example-repo-local/"
            allowInsecureProtocol = true
        }

**Comment by hassaanjamil** [comment]
@hamza94max I am planning to deploy the library on maven
